import { useEffect, useMemo, useState } from 'react';
import type { Contact, Draft, Job, Profile, Run, Schedule, Send, Settings } from '@gighunt/contracts';
import { api, bootstrap } from './api.js';

type View = 'search' | 'review' | 'history' | 'settings';
const emptyProfile: Omit<Profile, 'id'> = { name: '', email: '', summary: '', skills: [], targetRoles: [], locations: [], remote: true, confirmed: false };

export function App() {
  const [view, setView] = useState<View>('search'); const [profile, setProfile] = useState<Omit<Profile, 'id'>>(emptyProfile);
  const [settings, setSettings] = useState<Settings>(); const [runs, setRuns] = useState<Run[]>([]); const [jobs, setJobs] = useState<Job[]>([]);
  const [contacts, setContacts] = useState<Contact[]>([]); const [drafts, setDrafts] = useState<Draft[]>([]); const [sends, setSends] = useState<Send[]>([]);
  const [schedule, setSchedule] = useState<Schedule>(); const [query, setQuery] = useState('Senior TypeScript engineer remote'); const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [selectedDrafts, setSelectedDrafts] = useState<string[]>([]);

  async function refresh() {
    const [p, s, r, j, c, d, o, sc] = await Promise.all([api.profile(), api.settings(), api.runs(), api.jobs(), api.contacts(), api.drafts(), api.sends(), api.schedule()]);
    if (p) setProfile(p); setSettings(s); setRuns(r); setJobs(j); setContacts(c); setDrafts(d); setSends(o); setSchedule(sc);
  }
  useEffect(() => { bootstrap().then(refresh).catch((reason) => setError(reason.message)); const timer = setInterval(() => void refresh().catch(() => undefined), 3000); return () => clearInterval(timer); }, []);
  const counts = useMemo(() => ({ jobs: jobs.length, ready: drafts.length - sends.length, sent: sends.filter((send) => send.status === 'sent').length }), [jobs, drafts, sends]);
  async function act(action: () => Promise<unknown>) { setBusy(true); setError(''); try { await action(); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Request failed'); } finally { setBusy(false); } }
  async function saveApproveAndQueue(draft: Draft) {
    const revision = await api.updateDraft(draft.id, draft.subject, draft.body);
    await api.approve(revision.id); await api.send(revision.id);
  }
  async function approveSelectedBatch() {
    const selected = drafts.filter((draft) => selectedDrafts.includes(draft.id));
    const revisions = await Promise.all(selected.map((draft) => api.updateDraft(draft.id, draft.subject, draft.body)));
    await api.approveBatch(revisions.map((draft) => draft.id));
    await Promise.all(revisions.map((draft) => api.send(draft.id)));
    setSelectedDrafts([]);
  }

  if (!profile.confirmed) return <main className="onboarding"><div className="eyebrow">GIGHUNT / LOCAL AGENT</div><h1>Teach your search agent what matters.</h1><p className="lede">Your profile grounds every match and email. Confirm only facts you want the agent to use.</p>{error && <div className="error">{error}</div>}<form onSubmit={(event) => { event.preventDefault(); void act(() => api.saveProfile({ ...profile, confirmed: true })); }}><label>Name<input value={profile.name} onChange={(e) => setProfile({ ...profile, name: e.target.value })} required /></label><label>Email<input type="email" value={profile.email} onChange={(e) => setProfile({ ...profile, email: e.target.value })} required /></label><label>Professional summary<textarea value={profile.summary} onChange={(e) => setProfile({ ...profile, summary: e.target.value })} required /></label><label>Skills, comma separated<input value={profile.skills.join(', ')} onChange={(e) => setProfile({ ...profile, skills: e.target.value.split(',').map((x) => x.trim()).filter(Boolean) })} /></label><label>Target roles, comma separated<input value={profile.targetRoles.join(', ')} onChange={(e) => setProfile({ ...profile, targetRoles: e.target.value.split(',').map((x) => x.trim()).filter(Boolean) })} required /></label><button disabled={busy}>Confirm profile</button></form></main>;

  return <div className="shell"><aside><div className="brand"><span className="mark">G</span><div>GigHunt<small>Outreach agent</small></div></div><nav>{(['search', 'review', 'history', 'settings'] as View[]).map((item) => <button className={view === item ? 'active' : ''} onClick={() => setView(item)} key={item}>{item}</button>)}</nav><div className="agent-state"><span className={settings?.paused ? 'dot paused' : 'dot'} />{settings?.paused ? 'Paused' : 'Agent ready'}</div></aside><main><header><div><div className="eyebrow">YOUR PIPELINE</div><h1>{view === 'search' ? 'Find the right opening.' : view === 'review' ? 'Review every word.' : view === 'history' ? 'Outreach history.' : 'Agent controls.'}</h1></div><button className="secondary" onClick={() => void act(() => api.updateSettings({ paused: !settings?.paused }))}>{settings?.paused ? 'Resume agent' : 'Pause agent'}</button></header>{error && <div className="error">{error}</div>}
  {view === 'search' && <><section className="metrics"><article><strong>{counts.jobs}</strong><span>positions found</span></article><article><strong>{counts.ready}</strong><span>drafts ready</span></article><article><strong>{counts.sent}</strong><span>messages sent</span></article></section><form className="searchbox" onSubmit={(e) => { e.preventDefault(); void act(() => api.startRun(query)); }}><input aria-label="Job search" value={query} onChange={(e) => setQuery(e.target.value)} /><button disabled={busy || settings?.paused}>Start search</button></form><section><h2>Ranked positions</h2><div className="cards">{jobs.map((job) => { const matches = contacts.filter((contact) => contact.jobId === job.id); return <article className="job" key={job.id}><div className="score">{Math.round(job.score)}</div><div><h3>{job.title}</h3><p>{job.company} · {job.location}</p><small>{job.rationale}</small>{matches.map((contact) => <div className="evidence" key={contact.id}><span>{contact.name} · {contact.role} · {contact.email}</span><span>{contact.verified ? '✓ Email verified' : 'Email unverified'}</span><span>{contact.affiliationConfirmed ? '✓ Affiliation confirmed' : 'Affiliation needs human confirmation'}</span></div>)}</div><div className="actions"><a href={job.sourceUrl} target="_blank" rel="noreferrer">Source ↗</a><button className="secondary" disabled={busy} onClick={() => void act(() => api.researchContact(job.id))}>Research recruiter</button></div></article>; })}{jobs.length === 0 && <div className="empty">No positions yet. Start a focused search above.</div>}</div></section><section><h2>Recent runs</h2>{runs.slice(0, 5).map((run) => <div className="row" key={run.id}><span>{run.query}</span><span className="run-result"><span className={`status ${run.status}`}>{run.status === 'failed' ? 'failed' : run.stage}</span>{run.error && <small className="run-error">{run.error}</small>}</span></div>)}</section></>}
  {view === 'review' && <section><h2>Draft queue</h2>{settings?.approvalMode === 'batch' && <button disabled={busy || selectedDrafts.length === 0} onClick={() => void act(approveSelectedBatch)}>Save, approve & queue selected ({selectedDrafts.length})</button>}<div className="cards">{contacts.map((contact) => { const job = jobs.find((item) => item.id === contact.jobId); const draft = drafts.find((item) => item.contactId === contact.id); const evidenceLink = contact.affiliationEvidence && /^https:\/\//i.test(contact.affiliationEvidence) ? contact.affiliationEvidence : null; return <article className="review" key={contact.id}>{draft && settings?.approvalMode === 'batch' && <label><input type="checkbox" checked={selectedDrafts.includes(draft.id)} onChange={(e) => setSelectedDrafts(e.target.checked ? [...selectedDrafts, draft.id] : selectedDrafts.filter((id) => id !== draft.id))} /> Select for batch approval</label>}<div className="evidence"><span>{contact.verified ? '✓ Verified email' : 'Unverified email'}</span><span>Email evidence: {contact.emailEvidence ?? 'none'}</span><span>Affiliation source: {evidenceLink ? <a href={evidenceLink} target="_blank" rel="noreferrer">open evidence ↗</a> : contact.affiliationEvidence ?? 'none'}</span><span>{contact.affiliationConfirmed ? '✓ Human-confirmed affiliation' : 'Affiliation not confirmed'}</span>{contact.affiliationEvidence && !contact.affiliationConfirmed && <button className="secondary" onClick={() => void act(() => api.confirmAffiliation(contact.id))}>Confirm affiliation after review</button>}</div><h3>{job?.title} at {job?.company}</h3><p>To {contact.name} · {contact.email}</p>{draft ? <><input value={draft.subject} onChange={(e) => setDrafts(drafts.map((item) => item.id === draft.id ? { ...item, subject: e.target.value } : item))} /><textarea value={draft.body} onChange={(e) => setDrafts(drafts.map((item) => item.id === draft.id ? { ...item, body: e.target.value } : item))} /><div className="actions"><button className="secondary" onClick={() => void act(() => api.updateDraft(draft.id, draft.subject, draft.body))}>Save revision</button>{settings?.approvalMode !== 'batch' && <button onClick={() => void act(() => saveApproveAndQueue(draft))}>Save, approve & queue</button>}</div></> : <button onClick={() => job && void act(() => api.draft(job.id, contact.id))}>Create grounded draft</button>}</article>; })}{contacts.length === 0 && <div className="empty">Recruiter research will appear here.</div>}</div></section>}
  {view === 'history' && <section><h2>Send ledger</h2>{sends.map((send) => <div className="row" key={send.id}><span>{jobs.find((job) => job.id === send.jobId)?.title ?? send.jobId}</span><span className={`status ${send.status}`}>{send.status}</span>{send.status === 'uncertain' && <div className="actions"><button onClick={() => void act(() => api.reconcile(send.id, 'sent'))}>Mark sent</button><button className="secondary" onClick={() => void act(() => api.reconcile(send.id, 'cancelled'))}>Mark not sent</button></div>}</div>)}{sends.length === 0 && <div className="empty">No send attempts yet.</div>}</section>}
  {view === 'settings' && settings && schedule && <section className="settings"><h2>Policy</h2><label>Approval mode<select value={settings.approvalMode} onChange={(e) => void act(() => api.updateSettings({ approvalMode: e.target.value as Settings['approvalMode'] }))}><option value="individual">Individual review</option><option value="batch">Batch approval</option><option value="automatic">Automatic (verified only)</option></select></label><label>Daily send limit<input type="number" value={settings.dailySendLimit} onChange={(e) => setSettings({ ...settings, dailySendLimit: Number(e.target.value) })} onBlur={() => void act(() => api.updateSettings({ dailySendLimit: settings.dailySendLimit }))} /></label><h2>Schedule</h2><label className="toggle"><input type="checkbox" checked={schedule.enabled} onChange={(e) => { const next = { ...schedule, enabled: e.target.checked }; setSchedule(next); void act(() => api.saveSchedule(next)); }} /> Enable daily search</label><p className="muted">Cron: {schedule.cron} · Timezone: {schedule.timezone}</p></section>}</main></div>;
}
